# Version of docker-compose
version: "3"

services:
  app:
    build:
      context: . # Sets context to current directory
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: > # Defines the command for running project
      sh -c "python manage.py runserver 0.0.0.0:8000"
