# Generated by Django 3.0.7 on 2020-06-28 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Country',
        ),
    ]
